language: node_js
node_js:
- stable
branches:
  only:
  - publish
before_script:
- npm install -g firebase-tools
script:
- echo "Deploy!"
after_success:
- firebase deploy --token=$FIREBASE_TOKEN
env:
  global:
    secure: mOKmyOuXJvcnGGIie+MYrgIpwPRuH46xkotr/1JNzvTlG2lMkPZo41pBm1CPBBiNgWYYly/IArFcfaj8Hm8L+E39EX2jFoNco2bWfII8p1NT2sd9ozwQx4rJlt2gDo9gHa8ADljmpmux1iZVh8viwhCkThixpK/QmziHLZdVS3hZ/28y9XKQoFiXrOqANj/CpsXWqgHHWEcTpNrXBFwho6UQgnFeC6gi3rCOBmspT1btjbDRrItJqaLIhJOnA3VF193gm49qYgyAa3tXYDXZMgK5wELdIMcHquF0s50g5S9XvWvbdlmyiNyzqlK9bUOccWGcAbxn2GQl3VGDARJp1jNeQGVgEUuAFTqQlz641o7QGnc8soYos7U9oPSw5usOE2R++bZpwHVXKsBCijytpjJPXox2fwzt/NsnrpbLHy3+JZiFyBFzUG92CPZ2ZH0v5v92fC0MLAlQwWeNrTNzYOigBqfrJHIxuY+HV5YLIg0eKsFQxeRJyqwsT/CMCjZY+40vswS7tRBfMbXRu1XmoZAvSZRTSa+KIQHU5hYq7JtqMaG5aZg/AWtxls2e9Y8E2cMUEpSd90ecmee3pFgIQMeBYhKGMFifxLQA5X0a3B3Qw0fBDQ940SLogmKk1TYH1HX5g5nA90lzxnJUtaur4JDc3QA4qwhKuHM88ExlQOM=
